### ISSUE TITLE
GitHub Scheduled Process/Application

### ISSUE THREAD

**Issue by jbaskeen** [SETS-Interviews/divya-11202018#1]
### Description

Create a NodeJS application that runs a process every Monday at 7AM EST which retrieves the following data from GitHub for the public `node` repository (https://github.com/nodejs/node).

**Data to retrieve:**

- Number of open issues
- Number of branches
- Number of pull requests with the label `http`
  - Additionally, get the title of the open pull requests with this label

Once you have the data, print the information to the console in an easily readable format. How you format the output is up to you.

#### Goals

- The application should use the GitHub public API to retrieve the needed data
- The application should building and runnable in a docker image
  - i.e. `docker run <image_name>`
- Edit the project README.md to contain the necessary instructions in order to build and start the application
- Use the ocktokit library to interact with the GitHub API (https://github.com/octokit/rest.js/)
- Do not commit any personal credentials or API keys to this repository

### Submission

From the `master` branch, create a new feature branch and make your changes/commits on that new branch. When you have completed the project create a pull request and assign `@jbaskeen` as a reviewer of the pull request. Once you have created the pull request close this issue.

**Comment by Divyapuja** [comment]
Submitted the solution. Here is my PR - https://github.com/SETS-Interviews/divya-11202018/pull/2

Please review.
